# .github/release.yml
changelog:
  # exclude:
  #   labels:
  #     - ignore-for-release
  #   authors:
  #     - 
  categories:
    - title: Breaking Changes 🛠
      labels:
        - BREAKING CHANGE
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - feat
        - enhancement
    - title: Other Changes
      labels:
        - fix
        - chore
        - build
        - docs
        - ci
        - refactor
  
