---
  ##############################################################################
  ### Annotation
  ##############################################################################
  genome: ["ftp://ftp.ensembl.org/pub/release-89/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.chromosome.1.fa.gz",
           "ftp://ftp.ensembl.org/pub/release-89/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.chromosome.2.fa.gz"]
  annotation: ["ftp://ftp.ensembl.org/pub/release-89/gtf/homo_sapiens/Homo_sapiens.GRCh38.89.chr.gtf.gz"]
  other_RNA: "other.fa"
  ##############################################################################
  ### Output and log directories
  ##############################################################################
  output_dir: "results"
  local_log: "logs/local_log"
  cluster_log: "logs/cluster_log"
  ##############################################################################
  ### Options
  ##############################################################################
  sjdbOverhang: 100
  kmerLen: 31
...
