snakefile: "../../workflow/Snakefile"
cores: 4
printshellcmds: true
rerun-incomplete: true
use-conda: true
conda-frontend: conda
keep-going: true
notemp: true
no-hooks: true
verbose: true
restart-times: 0
default-resources: mem_mb=1024
resources: mem_mb=30000