name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - dev

jobs:

  snakemake-tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout zarp repository
        uses: actions/checkout@v2

      - name: Setup miniconda & zarp root env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7.4
          mamba-version: "0.16.0"
          channels: bioconda,conda-forge,defaults
          channel-priority: true
          auto-update-conda: false
          activate-environment: zarp
          environment-file: install/environment.root.yml
          auto-activate-base: false

      - name: Update zarp env with dev. packages
        run: mamba env update -f install/environment.dev.yml

      - name: Display all miniconda & env info
        run: |
          conda info -a
          conda list
      - name: Run test script for snakemake rulegraph
        run: bash tests/test_create_rule_graph/test.sh

      - name: Run test script for snakemake DAG
        run: bash tests/test_create_dag_image/test.sh

      - name: Run test local script
        run: bash tests/test_integration_workflow/test.local.sh
      
      - name: Run test script with temp flag
        run: bash tests/test_integration_workflow/test.temp.flag.sh
  
      - name: Run test local script for multilane samples
        run: bash tests/test_integration_workflow_multiple_lanes/test.local.sh

      - name: Run test local script with conda implementation
        run: bash tests/test_integration_workflow_with_conda/test.local.sh

      - name: Run SRA downloads workflow
        run: bash tests/test_sra_download_with_conda/test.local.sh
